/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  menu?: Array<
    {
      _key: string;
    } & PageReference
  >;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  mainImage?: MainImage;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type MainImage = {
  _type: "mainImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  caption?: string;
  alt?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  image?: MainImage;
  text?: BlockText;
  parallaxImage?: MainImage;
  enableContactForm?: boolean;
  enableGoogleMaps?: boolean;
};

export type BlockText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal";
  listItem?: never;
  markDefs?: null;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type CompanyInfo = {
  _id: string;
  _type: "companyInfo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  managingDirector?: string;
  orgNumber?: string;
  email?: string;
  phone?: string;
  address1?: string;
  address2?: string;
  zipCode?: string;
  city?: string;
  country?: string;
  googleMapsLatitude?: number;
  googleMapsLongitude?: number;
  googleMapsZoom?: number;
  socialMedias?: Array<
    {
      _key: string;
    } & SocialMedia
  >;
};

export type ServiceCategory = {
  _id: string;
  _type: "serviceCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  icon?:
    | "layers"
    | "brick-wall"
    | "truck"
    | "hammer"
    | "shovel"
    | "pickaxe"
    | "hard-hat"
    | "ruler"
    | "wrench"
    | "forklift";
  order?: number;
  pillarText?: string;
  description?: string;
  subServices?: Array<string>;
  image?: MainImage;
};

export type KontaktPage = {
  _id: string;
  _type: "kontaktPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: PageHero;
  formHeading?: string;
  formDescription?: string;
};

export type PageHero = {
  _type: "pageHero";
  eyebrow?: string;
  headline?: string;
  intro?: string;
};

export type OmOssPage = {
  _id: string;
  _type: "omOssPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: PageHero;
  story?: BlockText;
  image?: MainImage;
  statCards?: Array<
    {
      _key: string;
    } & Stat
  >;
  quote?: string;
  servicesSection?: {
    eyebrow?: string;
    heading?: string;
    outro?: string;
  };
  ctaTitle?: string;
};

export type TjenesterPage = {
  _id: string;
  _type: "tjenesterPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: PageHero;
  cta?: {
    title?: string;
    description?: string;
  };
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: PageHero;
  heroImage?: MainImage;
  trustStats?: Array<
    {
      _key: string;
    } & Stat
  >;
  pillars?: {
    eyebrow?: string;
    heading?: string;
    linkLabel?: string;
  };
  amberBand?: {
    eyebrow?: string;
    headline?: string;
    ctaLabel?: string;
  };
  gallery?: {
    eyebrow?: string;
    heading?: string;
    images?: Array<
      {
        _key: string;
      } & MainImage
    >;
  };
  contact?: {
    eyebrow?: string;
    heading?: string;
    intro?: string;
  };
};

export type Stat = {
  _type: "stat";
  value?: string;
  label?: string;
};

export type SocialMedia = {
  _type: "socialMedia";
  type?: "Facebook" | "Twitter" | "LinkedIn" | "GitHub";
  url?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | PageReference
  | SiteSettings
  | Service
  | SanityImageAssetReference
  | MainImage
  | Slug
  | Page
  | BlockText
  | CompanyInfo
  | ServiceCategory
  | KontaktPage
  | PageHero
  | OmOssPage
  | TjenesterPage
  | HomePage
  | Stat
  | SocialMedia
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: LAYOUT_QUERY
// Query: {  "info": *[_type == "companyInfo"][0]{    name, managingDirector, orgNumber,    address1, address2, zipCode, city, country, email, phone,    googleMapsLatitude, googleMapsLongitude,    socialMedias[]{ type, url }  }}
export type LAYOUT_QUERY_RESULT = {
  info: {
    name: string | null;
    managingDirector: string | null;
    orgNumber: string | null;
    address1: string | null;
    address2: string | null;
    zipCode: string | null;
    city: string | null;
    country: string | null;
    email: string | null;
    phone: string | null;
    googleMapsLatitude: number | null;
    googleMapsLongitude: number | null;
    socialMedias: Array<{
      type: "Facebook" | "GitHub" | "LinkedIn" | "Twitter" | null;
      url: string | null;
    }> | null;
  } | null;
};

// Source: src/sanity/lib/queries.ts
// Variable: HOME_QUERY
// Query: {  "page": *[_id == "homePage"][0]{    hero, heroImage, trustStats, pillars, amberBand, gallery, contact  },  "services": *[_type == "serviceCategory"] | order(order asc){    _id, title, icon, pillarText  }}
export type HOME_QUERY_RESULT = {
  page:
    | {
        hero: null;
        heroImage: null;
        trustStats: null;
        pillars: null;
        amberBand: null;
        gallery: null;
        contact: null;
      }
    | {
        hero: PageHero | null;
        heroImage: null;
        trustStats: null;
        pillars: null;
        amberBand: null;
        gallery: null;
        contact: null;
      }
    | {
        hero: PageHero | null;
        heroImage: MainImage | null;
        trustStats: Array<
          {
            _key: string;
          } & Stat
        > | null;
        pillars: {
          eyebrow?: string;
          heading?: string;
          linkLabel?: string;
        } | null;
        amberBand: {
          eyebrow?: string;
          headline?: string;
          ctaLabel?: string;
        } | null;
        gallery: {
          eyebrow?: string;
          heading?: string;
          images?: Array<
            {
              _key: string;
            } & MainImage
          >;
        } | null;
        contact: {
          eyebrow?: string;
          heading?: string;
          intro?: string;
        } | null;
      }
    | null;
  services: Array<{
    _id: string;
    title: string | null;
    icon:
      | "brick-wall"
      | "forklift"
      | "hammer"
      | "hard-hat"
      | "layers"
      | "pickaxe"
      | "ruler"
      | "shovel"
      | "truck"
      | "wrench"
      | null;
    pillarText: string | null;
  }>;
};

// Source: src/sanity/lib/queries.ts
// Variable: TJENESTER_QUERY
// Query: {  "page": *[_id == "tjenesterPage"][0]{ hero, cta },  "services": *[_type == "serviceCategory"] | order(order asc){    _id, title, icon, description, subServices, image  }}
export type TJENESTER_QUERY_RESULT = {
  page:
    | {
        hero: null;
        cta: null;
      }
    | {
        hero: PageHero | null;
        cta: null;
      }
    | {
        hero: PageHero | null;
        cta: {
          title?: string;
          description?: string;
        } | null;
      }
    | null;
  services: Array<{
    _id: string;
    title: string | null;
    icon:
      | "brick-wall"
      | "forklift"
      | "hammer"
      | "hard-hat"
      | "layers"
      | "pickaxe"
      | "ruler"
      | "shovel"
      | "truck"
      | "wrench"
      | null;
    description: string | null;
    subServices: Array<string> | null;
    image: MainImage | null;
  }>;
};

// Source: src/sanity/lib/queries.ts
// Variable: OM_QUERY
// Query: {  "page": *[_id == "omOssPage"][0]{    hero, story, image, statCards, quote, servicesSection, ctaTitle  },  "services": *[_type == "serviceCategory"] | order(order asc){ subServices }}
export type OM_QUERY_RESULT = {
  page:
    | {
        hero: null;
        story: null;
        image: null;
        statCards: null;
        quote: null;
        servicesSection: null;
        ctaTitle: null;
      }
    | {
        hero: null;
        story: null;
        image: MainImage | null;
        statCards: null;
        quote: null;
        servicesSection: null;
        ctaTitle: null;
      }
    | {
        hero: PageHero | null;
        story: null;
        image: null;
        statCards: null;
        quote: null;
        servicesSection: null;
        ctaTitle: null;
      }
    | {
        hero: PageHero | null;
        story: BlockText | null;
        image: MainImage | null;
        statCards: Array<
          {
            _key: string;
          } & Stat
        > | null;
        quote: string | null;
        servicesSection: {
          eyebrow?: string;
          heading?: string;
          outro?: string;
        } | null;
        ctaTitle: string | null;
      }
    | null;
  services: Array<{
    subServices: Array<string> | null;
  }>;
};

// Source: src/sanity/lib/queries.ts
// Variable: KONTAKT_QUERY
// Query: {  "page": *[_id == "kontaktPage"][0]{ hero, formHeading, formDescription }}
export type KONTAKT_QUERY_RESULT = {
  page:
    | {
        hero: null;
        formHeading: null;
        formDescription: null;
      }
    | {
        hero: PageHero | null;
        formHeading: null;
        formDescription: null;
      }
    | {
        hero: PageHero | null;
        formHeading: string | null;
        formDescription: string | null;
      }
    | null;
};

// Source: src/sanity/lib/queries.ts
// Variable: SITEMAP_QUERY
// Query: {  "home": *[_id == "homePage"][0]._updatedAt,  "tjenester": *[_id == "tjenesterPage"][0]._updatedAt,  "omOss": *[_id == "omOssPage"][0]._updatedAt,  "kontakt": *[_id == "kontaktPage"][0]._updatedAt,  "servicesUpdatedAt": *[_type == "serviceCategory"] | order(_updatedAt desc)[0]._updatedAt}
export type SITEMAP_QUERY_RESULT = {
  home: string | null;
  tjenester: string | null;
  omOss: string | null;
  kontakt: string | null;
  servicesUpdatedAt: string | null;
};

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '{\n  "info": *[_type == "companyInfo"][0]{\n    name, managingDirector, orgNumber,\n    address1, address2, zipCode, city, country, email, phone,\n    googleMapsLatitude, googleMapsLongitude,\n    socialMedias[]{ type, url }\n  }\n}': LAYOUT_QUERY_RESULT;
    '{\n  "page": *[_id == "homePage"][0]{\n    hero, heroImage, trustStats, pillars, amberBand, gallery, contact\n  },\n  "services": *[_type == "serviceCategory"] | order(order asc){\n    _id, title, icon, pillarText\n  }\n}': HOME_QUERY_RESULT;
    '{\n  "page": *[_id == "tjenesterPage"][0]{ hero, cta },\n  "services": *[_type == "serviceCategory"] | order(order asc){\n    _id, title, icon, description, subServices, image\n  }\n}': TJENESTER_QUERY_RESULT;
    '{\n  "page": *[_id == "omOssPage"][0]{\n    hero, story, image, statCards, quote, servicesSection, ctaTitle\n  },\n  "services": *[_type == "serviceCategory"] | order(order asc){ subServices }\n}': OM_QUERY_RESULT;
    '{\n  "page": *[_id == "kontaktPage"][0]{ hero, formHeading, formDescription }\n}': KONTAKT_QUERY_RESULT;
    '{\n  "home": *[_id == "homePage"][0]._updatedAt,\n  "tjenester": *[_id == "tjenesterPage"][0]._updatedAt,\n  "omOss": *[_id == "omOssPage"][0]._updatedAt,\n  "kontakt": *[_id == "kontaktPage"][0]._updatedAt,\n  "servicesUpdatedAt": *[_type == "serviceCategory"] | order(_updatedAt desc)[0]._updatedAt\n}': SITEMAP_QUERY_RESULT;
  }
}
